---
title: "Article 1"
description: |
  Whales at risk.
author:
  - name: Ludivine Demoulin
    url: {https://www.bbc.com/news/science-environment-54485407}
date: 10-23-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# 'Real and imminent' extinction risk to whales

## 1.Description

- Source of the article : https://www.bbc.com/news/science-environment-54485407
- Date : 10 October 2020.
- Word count : 726

## 2.Vocabulary

| Word from the text | Synonym/definition in English | French translation |
| --- | --- | --- |
| porpoises | Marine animal | marsouins |
| Lack | deficiency | Manquer de |
| across | past | à travers |
| to recover | recuperate | s'en remettre |
| wildlife | fauna | faune |
| the path | trail, track | le chemin |
| to avoid| keep away | éviter |
| the trend | tendency | la tendance |

## 3.Analysis table about the study

| Questions | Answers |
| --- | --- |
| Researches ? | Write by Helen Briggs. More than 350 scientists have agreed to protect whales |
| Published in ? when (if mentioned) | Published in BBC news, the 10 October 2020 |
| General topic | Scientists are clear on this subject, the extinction of whales is imminent. In question, the global warming, the pollution of the seas and its overexploitation but the greatest danger is to be caught in the fishing nets. |
| Procedure/what was examined | In 1970 and 1980, there was a "Save the whales" protest to stop commercial whaling. This year, a petition is underway to protect whales. The petition has already been signed by more than 350 scientists and environmentalists from 40 countries.|
| Conclusions/discovery | Thanks to the protests of 1970 and 1980, commercial whaling was prohibited. But there is still a long way to go before we have any real results. |
| Remaining questions | / |
